export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REFRESH_ACCESSTOKEN = "REFRESH_ACCESSTOKEN";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ACCESSTOKEN_REQUEST = "ACCESSTOKEN_REQUEST";
export const ACCESSTOKEN_SUCCESS = "ACCESSTOKEN_SUCCESS";
export const ACCESSTOKEN_FAIL = "ACCESSTOKEN_FAIL";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const RESET_SEARCH_REQUEST = "RESET_SEARCH_REQUEST";
export const RESET_SEARCH_SUCCESS = "RESET_SEARCH_SUCCSS";
export const RESET_SEARCH_FAIL = "RESET_SEARCH_FAIL";
export const RESET_EMAIL_REQUEST = "RESET_EMAIL_REQUIEST";
export const RESET_EMAIL_SUCCESS = "RESET_EMAIL_SUCCESS";
export const RESET_EMAIL_FAIL = "RESET_EMAIL_FAIL";
export const RESET_CODE_REQUEST = "RESET_CODE_REQUEST";
export const RESET_CODE_SUCCESS = "RESET_CODE_SUCCESS";
export const RESET_CODE_FIAL = "RESET_CODE_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FIAL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CANCEL = "RESET_PASSWORD_CANCEL";
