export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REFRESH_ACCESSTOEKN = "REFRESH_ACCESSTOEKN";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";
export const CHANGE_USER_PICTURE = "CHANGE_USER_PICTURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ACCESSTOKEN_REQUEST = "ACCESSTOKEN_REQUEST";
export const ACCEESSTOKEN_SUCCESS = "ACCEESSTOKEN_SUCCESS";
export const ACCESSTOKEN_FAIL = "ACCESSTOKEN_FAIL";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const RESET_SEARCH_REQUSET = "RESET_SEARCH_REQUEST";
export const RESET_SEARCH_SUCCESS = "RESET_SEARCH_SUCCESS";
export const RESET_SEARCH_FAIL = "RESET_SEARCH_FAIL";
export const RESET_EMAIL_REQUEST = "RESET_EMAIL_REQUEST";
export const RESET_EMAIL_SUCCESS = "RESET_EMAIL_SUCCESS";
export const RESET_EMAIL_FAIL = "RESET_EMAIL_FAIL";
export const RESET_CODE_REQUEST = "RESET_CODE_REQUEST";
export const RESET_CODE_SUCCESS = "RESET_CODE_SUCCESS";
export const RESET_CODE_FAIL = "RESET_CODE_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CANCEL = "RESET_PASSWORD_CANCEL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FIAL = "CREATE_POST_FAIL";
export const UPLOAD_POST_IMAGE_REQUEST = "UPLOAD_POST_IMAGE_REQUEST";
export const UPLOAD_POST_IMAGE_SUCCESS = "UPLOAD_POST_IMAGE_SUCCESS";
export const UPLOAD_POST_IMAGE_FAIL = "UPLOAD_POST_IMAGE_FAIL";
export const CLEAR_POST_INFO = "CRLEAR_POST_INFO";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCES = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_POSTS_CLEAN = "GET_POSTS_CLEAN";
export const ADD_NEW_POST = "ADD_NEW_POST";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_CLEAR = "GET_PROFILE_CLEAR";
export const CHANGE_PROFILE_COVER = "CHANGE_PROFILE_COVER";
export const CHANGE_PROFILE_PICTURE = "CHANGE_PROFILE_PICTURE";
export const CHANGE_PROFILE_DETAILS = "CHANGE_PROFILE_DETAILS";

export const SET_COVER_REQUEST = "SET_COVER_REQUEST";
export const SET_COVER_SUCCESS = "SET_COVER_SUCCESS";
export const SET_COVER_FAIL = "SET_COVER_FAIL";
export const SET_COVER_CLEAR = "SET_COVER_CLEAR";

export const GET_MYPOSTS_REQUEST = "GET_MYPOST_REQUEST";
export const GET_MYPOSTS_SUCCESS = "GET_MYPOST_SUCCESS";
export const GET_MYPOSTS_FAIL = "GET_MYPOST_FAIL";
export const GET_MYPOSTS_CLEAN = "GET_MYPOST_CLEAN";
export const ADD_NEW_MYPOST = "ADD_NEW_MYPOST";
