export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REFRESH_ACCESSTOKEN = "REFRESH_ACCESSTOKEN";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


export const ACCESSTOKEN_REQUEST = "ACCESSTOKEN_REQUEST";
export const ACCESSTOKEN_SUCCESS = "ACCESSTOKEN_SUCCESS";
export const ACCESSTOKEN_FAIL = "ACCESSTOKEN_FAIL";
